input: /home/is/tomohiro-ni/project/SIP/experiment/20240808_EVEampeleBasedCoding/data/DISEASE_test.xlsx
output: output.xlsx
id: ID
source: 出現形
target: 正規形
flag_col: 正規形_flag
source_flag: S,A,B,C
target_flag: D,nan
flag_overwrite: False
threshold: 90
eval: True
eval_data_count: 999999999
inference: True